name: Build APK

on:
  #push:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash:
        (注意：与 https://github.com/rosebe/AndroidLibXrayLite/blob/alpn_h2/go.mod 中的
        replace github.com/xtls/xray-core v1.8.1 => github.com/rosebe/xray-core 994e87cbe103 commit id 的一致性)'
        required: false
        default: '994e87cbe103'
        
env:
  TZ: Asia/Shanghai
  ALIAS: ${{ secrets.ALIAS }}
  KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
  KEYSTOREPASSWORD: ${{ secrets.KEYSTOREPASSWORD }}
  SIGNINGKEYBASE64: ${{ secrets.SIGNINGKEYBASE64 }}

  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      
    - name: Setup Java
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'temurin'
        #java-version: '17'
        java-version: '21'
        cache: 'gradle'
    #- run: ./gradlew build --no-daemon

    - name: Get go.sum
      run: |
        curl -L "https://github.com/rosebe/v2rayNG/raw/refs/heads/Generate_apk_signing_certificate_with_keytool/go.sum" -o go.sum

    - name: Setup Golang
      uses: actions/setup-go@v5.2.0
      with:
        go-version: '1.22.4'
        check-latest: false
        cache: true
        #cache-dependency-path: "/home/runner/go/pkg/mod/**/*.sum"
    
    #- name: Patch Go use 600296
      #https://go-review.googlesource.com/c/go/+/600296
      #run: |
        #cd "$(go env GOROOT)"
        #curl "https://go-review.googlesource.com/changes/go~600296/revisions/5/patch" | base64 -d | patch --verbose -p 1
 
    - name: Set Golang-version 
      run: |
        echo "GOLANG-VERSION=$(go version | grep -Eo '[0-9]\.[0-9]+\.[0-9]+')" >> $GITHUB_ENV
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20240806205939-81131f6468ab
        #go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Setup Android environment SDK
      uses: android-actions/setup-android@v3.2.2
  
    #- name: Setup VpnService.kt patch
      #run: |
        #sed -i "s/VPN_MTU = 1500/VPN_MTU = 9000/" ${{ github.workspace }}/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt
        #sed -i 's/PRIVATE_VLAN4_CLIENT = "26.26.26.1"/PRIVATE_VLAN4_CLIENT = "10.1.1.1"/' ${{ github.workspace }}/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt
        #sed -i 's/PRIVATE_VLAN4_ROUTER = "26.26.26.2"/PRIVATE_VLAN4_ROUTER = "10.1.1.2"/' ${{ github.workspace }}/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt
        #sed -i 's/PRIVATE_VLAN6_CLIENT = "da26:2626::1"/PRIVATE_VLAN6_CLIENT = "::ffff:a01:101"/' ${{ github.workspace }}/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt
        #sed -i 's/PRIVATE_VLAN6_ROUTER = "da26:2626::2"/PRIVATE_VLAN6_ROUTER = "::ffff:a01:102"/' ${{ github.workspace }}/V2rayNG/app/src/main/kotlin/com/v2ray/ang/service/V2RayVpnService.kt

    - name: Set Build Time 
      run: |
        echo "BUILD_TIME=$(date +%Y_%m_%d-%H:%M:%S)" >> $GITHUB_ENV
        
    - name: Build dependencies
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b alpn_h2 https://github.com/rosebe/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        #sed -i "s/go 1.22.2/go 1.22.4/" go.mod
        sed -i "s/github.com\/rosebe\/xray-core 994e87cbe103/github.com\/rosebe\/xray-core ${{ github.event.inputs.XRAY_CORE_VERSION }}/" go.mod
        sed -i "s/v2core.Version())/v2core.Version() + \" Rosebe_alpn_h2 @${{ github.event.inputs.XRAY_CORE_VERSION }}, build on ${{ env.BUILD_TIME }}, by Golang ${{ env.GOLANG-VERSION }}. \")/" libv2ray_main.go                                                                                                                   
        go get github.com/rosebe/xray-core@${{ github.event.inputs.XRAY_CORE_VERSION }} || true
        gomobile clean
        gomobile init
        go mod tidy -v
        gomobile bind -a -v -androidapi 21 -ldflags='-s -w' ./
        cp *.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Upload go.mod
      uses: actions/upload-artifact@v4.5.0
      if: ${{  success() }}
      with:
        name: go.mod
        path: |
          ${{ github.workspace }}/build/AndroidLibXrayLite/go.mod

    - name: Upload go.sum
      uses: actions/upload-artifact@v4.5.0
      if: ${{  success() }}
      with:
        name: go.sum
        path: |
          ${{ github.workspace }}/build/AndroidLibXrayLite/go.sum                  

    - name: List xray path
      run: |
        find /home/runner/go/pkg/mod/github.com/  -type f -exec du -h {} \; | grep ${{ github.event.inputs.XRAY_CORE_VERSION }}/core/core.go
        echo "Xray_Source_Path=$(find /home/runner/go/pkg/mod/github.com/  -type f -exec du -h {} \; | grep ${{ github.event.inputs.XRAY_CORE_VERSION }}/core/core.go | awk '{print $2}' )" >> $GITHUB_ENV
    
    - name: Set variables
      id: step_one
      shell: bash
      run: |
          echo "Xray_Version_x=$(cat ${{ env.Xray_Source_Path }} | grep 'Version_x byte =' | awk '{print $4}') " >> $GITHUB_ENV
          echo "Xray_Version_y=$(cat ${{ env.Xray_Source_Path }} | grep 'Version_y byte =' | awk '{print $4}') " >> $GITHUB_ENV
          echo "Xray_Version_z=$(cat ${{ env.Xray_Source_Path }} | grep 'Version_z byte =' | awk '{print $4}') " >> $GITHUB_ENV
 
          cp ${{ github.workspace }}/V2rayNG/app/build.gradle.kts ./build.gradle.tmp
          sed -i 's/\"//g' ./build.gradle.tmp
          echo "NG_VERSION=$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $3}')" >> $GITHUB_ENV
          echo "NG_VERSION: ${{ env.NG_VERSION }}"
          
          echo "ASSET_NAME=v2rayNG_v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $3}')" >> $GITHUB_ENV
          echo "TAG_NAME=v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $3}').$(((`date -d "$(date "+%Y-%m-%d %H:%M:%S")" +%s`*1000+10#`date "+%N"`/1000000)/1000))" >> $GITHUB_ENV
          echo "RELEASE_NAME=v2rayNG_v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $3}') build on ${{ env.BUILD_TIME }}" >> $GITHUB_ENV
          rm -rf ./build.gradle.tmp

    #- name: Decode Keystore
      #uses: timheuer/base64-to-file@v1
      #id: android_keystore
      #with:
        #fileName: "android_keystore.jks"
        #encodedString: ${{ secrets.SIGNINGKEYBASE64 }}                
    
    - name: Build APK
      run: |
        #sed -i "s/gradle-8.9-bin.zip/gradle-8.11-bin.zip/" ${{ github.workspace }}/V2rayNG/gradle/wrapper/gradle-wrapper.properties
        cd ${{ github.workspace }}/V2rayNG
        #chmod 777 *
        #sed -i 's/org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/' ${{ github.workspace }}/V2rayNG/gradle.properties
        chmod 755 gradlew
        #./gradlew build --no-daemon
        ./gradlew assembleRelease --no-daemon
        #./gradlew assembleRelease
        #./gradlew assembleRelease --no-daemon \
        #                          -Pandroid.injected.signing.store.file=${{ steps.android_keystore.outputs.filePath }} \
        #                          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTOREPASSWORD }} \
        #                          -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} \
        #                          -Pandroid.injected.signing.key.password=${{ secrets.KEYPASSWORD }}
           
    - name: List APK files
      run: |
        find V2rayNG/app/build/outputs/apk/ -type f -exec du -h {} \;

    - name: Sign APK files
      uses: ilharp/sign-android-release@nightly
      with:
        releaseDir: V2rayNG/app/build/outputs/apk/playstore/release/
        keyAlias: ${{ env.ALIAS }}
        keyPassword: ${{ env.KEYPASSWORD }}
        keyStorePassword: ${{ env.KEYSTOREPASSWORD }}
        signingKey: ${{ env.SIGNINGKEYBASE64 }}
        buildToolsVersion: 35.0.0   
    
    - name: Upload APK
      uses: actions/upload-artifact@v4.5.0
      if: ${{  success() }}
      with:
        name: apk
        path: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/playstore/release/v2rayNG_*_arm64-v8a-signed.apk
          
    - name: Upload binaries [ arm64-v8a*signed.apk ] to release
      uses: svenstaro/upload-release-action@e2a63377780a8bacc68dcac9b0979ee20ad5a791
      #if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}          
        tag: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        #asset_name: ${{ env.ASSET_NAME }}
        file: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/playstore/release/v2rayNG_*arm64-v8a*signed.apk
          
        body: "### Happy play for v2rayNG_v${{ env.NG_VERSION }} with alpn_h2 
        
               ### Go Compiler && Toolchain : Golang ${{ env.GOLANG-VERSION }}

              - [ ] [Xray core ( __Rosebe__ )](https://github.com/rosebe/Xray-core/commit/${{ github.event.inputs.XRAY_CORE_VERSION }}) version or commit ID =>> V${{ env.Xray_Version_x }}.${{ env.Xray_Version_y }}.${{ env.Xray_Version_z }} @${{ github.event.inputs.XRAY_CORE_VERSION }}
              
              
              "
        overwrite: true
        file_glob: true

    - name: Upload binaries [ armeabi-v7a*signed.apk ] to release
      uses: svenstaro/upload-release-action@e2a63377780a8bacc68dcac9b0979ee20ad5a791
      #if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}          
        tag: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        #asset_name: ${{ env.ASSET_NAME }}
        file: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/playstore/release/v2rayNG_*armeabi-v7a*signed.apk
                           
        body: "### Happy play for v2rayNG_v${{ env.NG_VERSION }} with alpn_h2 
        
               ### Go Compiler && Toolchain : Golang ${{ env.GOLANG-VERSION }}

              - [ ] [Xray core ( __Rosebe__ )](https://github.com/rosebe/Xray-core/commit/${{ github.event.inputs.XRAY_CORE_VERSION }}) version or commit ID =>> V${{ env.Xray_Version_x }}.${{ env.Xray_Version_y }}.${{ env.Xray_Version_z }} @${{ github.event.inputs.XRAY_CORE_VERSION }}
              
              
              "
        overwrite: true
        file_glob: true
    
    - name: Upload binaries [ x86*signed.apk and x86_64*signed.apk ] to release
      uses: svenstaro/upload-release-action@e2a63377780a8bacc68dcac9b0979ee20ad5a791
      #if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}          
        tag: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        #asset_name: ${{ env.ASSET_NAME }}
        file: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/playstore/release/*x86*signed.apk
                  
        body: "### Happy play for v2rayNG_v${{ env.NG_VERSION }} with alpn_h2 
        
               ### Go Compiler && Toolchain : Golang ${{ env.GOLANG-VERSION }}

              - [ ] [Xray core ( __Rosebe__ )](https://github.com/rosebe/Xray-core/commit/${{ github.event.inputs.XRAY_CORE_VERSION }}) version or commit ID =>> V${{ env.Xray_Version_x }}.${{ env.Xray_Version_y }}.${{ env.Xray_Version_z }} @${{ github.event.inputs.XRAY_CORE_VERSION }}
              
              
              "
        overwrite: true
        file_glob: true
    
    - name: Upload binaries [ universal*signed.apk ] to release
      uses: svenstaro/upload-release-action@e2a63377780a8bacc68dcac9b0979ee20ad5a791
      #if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}          
        tag: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }}
        #asset_name: ${{ env.ASSET_NAME }}
        file: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/playstore/release/*universal*signed.apk
        
        body: "### Happy play for v2rayNG_v${{ env.NG_VERSION }} with alpn_h2 
        
               ### Go Compiler && Toolchain : Golang ${{ env.GOLANG-VERSION }}

              - [ ] [Xray core ( __Rosebe__ )](https://github.com/rosebe/Xray-core/commit/${{ github.event.inputs.XRAY_CORE_VERSION }}) version or commit ID =>> V${{ env.Xray_Version_x }}.${{ env.Xray_Version_y }}.${{ env.Xray_Version_z }} @${{ github.event.inputs.XRAY_CORE_VERSION }}
              
              
              "
        overwrite: true
        file_glob: true
