  


    - name: Build dependencies
      run: |
        mkdir ${{ github.workspace }}/build
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b main https://github.com/2dust/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        go get github.com/xtls/xray-core@${{ github.event.inputs.XRAY_CORE_VERSION }} || true
        gomobile init
        go mod tidy -v
        gomobile bind -v -androidapi 19 -ldflags='-s -w' ./
        cp *.aar ${{ github.workspace }}/V2rayNG/app/libs/


    - name: Set variables
      id: step_one
      shell: bash
      run: |
          cp ${{ github.workspace }}/V2rayNG/app/build.gradle ./build.gradle.tmp
          sed -i 's/\"//g' ./build.gradle.tmp
          echo "NG_VERSION=$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $2}')" >> $GITHUB_ENV
          echo "NG_VERSION: ${{ env.NG_VERSION }}"
          
          echo "ASSET_NAME=v2rayNG_v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $2}')" >> $GITHUB_ENV
          echo "TAG_NAME=v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $2}')" >> $GITHUB_ENV
          echo "RELEASE_NAME=v2ray-ng-v$(cat ./build.gradle.tmp | grep versionName | grep -v versionNameSuffix |grep -v variant.versionName | awk '{print $2}')" >> $GITHUB_ENV
          rm -rf ./build.gradle.tmp
    
          
    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 777 *
        sed -i 's/org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8/' ${{ github.workspace }}/V2rayNG/gradle.properties
        ./gradlew assembleDebug
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: |
          ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/v2rayNG_${{ env.NG_VERSION }}_arm64-v8a.apk
          
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.7.0
      #if: github.event_name == 'release'
      with:
        repo_token: ${{ github.token }}          
        tag: ${{ env.TAG_NAME }}
        release_name: ${{ env.RELEASE_NAME }} Xray-core commit id:${{ github.event.inputs.XRAY_CORE_VERSION }} build on $(date +%Y_%m_%d-%H:%M:%S)
        #asset_name: ${{ env.ASSET_NAME }}
        file: |
            ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/debug/v2rayNG_${{ env.NG_VERSION }}_*.apk
        body: "### Happy play for v2ray-ng-v${{ env.NG_VERSION }} 


             - [ ] [Xray core](https:github.com/XTLS/Xray-core/commit/${{ github.event.inputs.XRAY_CORE_VERSION }}) version or commit ID =>> ${{ github.event.inputs.XRAY_CORE_VERSION }}

              "
        overwrite: true
        file_glob: true
