#https://github.com/actions/gh-actions-cache/issues/20

name: cleanup caches by a branch
on:
  workflow_dispatch:
  
  #pull_request:
    #types:
      #- closed

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: List and Cleanup
        run: |
          gh extension install actions/gh-actions-cache
          
          echo "Lists of cache:"
          gh cache list
          
          echo "Fetching list of cache key"
          #cacheKeysForPR=$(gh cache list --ref $BRANCH --limit 100 --json id --jq '.[].id')
          gh cache list --limit 100 | awk '{print $1}'
          #gh cache list --limit 100 | grep "keyword" | awk '{print $1}' | xargs -I {} gh cache delete {}
          #cacheKeysForPRtest=$(gh cache list --limit 100 | awk '{print $1}')
          cacheKeysForPR=$(gh cache list --limit 100 | awk '{print $1}')
          
          #echo "lists of cache key [@]"
          #${cacheKeysForPRtest[@]}
          #${!cacheKeysForPRtest[@]}
          #${#cacheKeysForPRtest[@]} 
          
          #echo "lists of cache key [*] "
          #${cacheKeysForPRtest[*]}
          #${!cacheKeysForPRtest[*]}
          #${#cacheKeysForPRtest[*]}
                     
          
          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeysForPR
          do
              gh cache delete $cacheKey
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge
